# Generated by Django 4.2.3 on 2023-07-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherRecords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station_id", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("max_temp", models.IntegerField()),
                ("min_temp", models.IntegerField()),
                ("ppt_amount", models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="weatherrecords",
            unique_together={("station_id", "date")},
        ),
    ]
