# Generated by Django 4.2.3 on 2023-07-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherStationStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station_id", models.CharField(max_length=255)),
                ("year", models.CharField()),
                ("max_temp_avg", models.FloatField()),
                ("min_temp_avg", models.FloatField()),
                ("total_ppt", models.IntegerField()),
            ],
            options={
                "unique_together": {("station_id", "year")},
            },
        ),
    ]
