# Generated by Django 4.2.3 on 2023-07-08 22:59

from django.db import migrations
from utils.migration_utils import MigrationUtils


def forward_func(apps, schema_editor):
    weather_records = apps.get_model("weather_app", "WeatherRecords")
    db_alias = schema_editor.connection.alias
    model_data_to_upload = []
    utils = MigrationUtils()
    records = utils.traverse_data_dir(get_file_data=True)
    for record in records:
        model_data_to_upload.append(weather_records(**record))
    weather_records.objects.using(db_alias).bulk_create(model_data_to_upload)


def reverse_func(apps, schema_editor):
    weather_records = apps.get_model("weather_app", "WeatherRecords")
    db_alias = schema_editor.connection.alias
    utils = MigrationUtils()
    station_ids = utils.traverse_data_dir(get_station_ids=True)
    weather_records.objects.using(db_alias).filter(station_id__in=station_ids).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("weather_app", "0002_weatherstationstats"),
    ]

    operations = [migrations.RunPython(forward_func, reverse_func)]
