# Generated by Django 4.2.3 on 2023-07-10 21:16

from django.db import migrations
from utils.stats_utils import StatsUtils


def forwards_func(apps, schema_editor):
    weather_records = apps.get_model("weather_app", "WeatherRecords")
    db_alias = schema_editor.connection.alias

    get_records = (
        weather_records.objects.using(db_alias)
        .values("station_id", "date__year")
        .distinct()
    )
    for record in get_records:
        StatsUtils.create_weather_stats(
            station_id=record.get("station_id"), year=record.get("date__year")
        )


def reverse_func(apps, schema_editor):
    weather_stats = apps.get_model("weather_app", "WeatherStationStats")
    db_alias = schema_editor.connection.alias
    weather_stats.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("weather_app", "0003_weather_data_ingestion"),
    ]

    operations = [migrations.RunPython(forwards_func, reverse_func)]
